In [2]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [6]:
data = pd.read_csv('data/car.data')
print(data.head(8))

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc
5  vhigh  vhigh     2       2      med   high  unacc
6  vhigh  vhigh     2       2      big    low  unacc
7  vhigh  vhigh     2       2      big    med  unacc


In [13]:
x = data[[
    'buying',
    'maint',
    'safety'
]].values

y = data[['class']]

#print(x,y)

#convert the data into numbers
Le = LabelEncoder()
for i in range(len(x[0])):
    x[:,i] = Le.fit_transform(x[:,i])
    
print(x)

label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}

y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


/home/leroth/Projects/scikit/scikit-course/lib/python3.6/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


In [15]:
knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

knn.fit(x_train, np.ravel(y_train)) # Changed shape from column vector to array with ravel

prediction = knn.predict(x_test)

accuracy = metrics.accuracy_score(y_test, prediction)

print('predictions: ',prediction)
print('accuracy: ',accuracy)

predictions:  [1 0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 2 0 0 1 0 2 3 0 0 0
 0 1 0 0 1 0 0 0 0 1 0 1 2 0 0 0 0 0 0 0 0 1 2 1 0 0 0 0 1 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 3 0 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 2 0 0 1 0 1 0 0 1 0 1 0 1 0 0 2 0 1 1 0 0 0 0
 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 2 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1
 0 0 2 1 1 0 0 0 0 0 2 0 0 2 0 0 0 0 0 0 1 0 3 3 0 0 1 0 0 0 1 0 0 0 0 0 0
 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 2 0 1 0 0 0 0 0 0 0 2 0 1
 0 3 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 3 0 1 1 0 0 0 0 0 0 1 0
 0 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 3 1 0 2 1 1 3 0 1
 0 0 0 0 0 0 0 1 0 0 3 0 1]
accuracy:  0.7254335260115607


In [18]:
a = 17
print("actual value: ", y[a])
print('predicted value: ',knn.predict(x)[a])

actual value:  [0]
predicted value:  0
