In [24]:
from PIL import Image
import numpy as np
import mnist
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [25]:
# training

x_train = mnist.train_images()
y_train = mnist.train_labels()

In [26]:
x_test = mnist.test_images()
y_test = mnist.test_labels()

In [27]:
print(x_train.ndim)

3


In [28]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [29]:
x_train = x_train.reshape((-1,28*28))
x_test = x_test.reshape((-1,28*28))
print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


In [30]:
#Normalize data
x_train = x_train/256
x_test = x_test/256

In [31]:
clf = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(64,64))

In [32]:
clf.fit(x_train,y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [42]:
predictions = clf.predict(x_test)
#print(predictions.shape)
#print(y_test.shape)
acc = confusion_matrix(y_test, predictions)
print(acc)

[[ 970    0    0    1    2    1    3    2    1    0]
 [   0 1126    3    0    0    0    1    1    4    0]
 [   3    1 1011    5    2    0    0    4    6    0]
 [   0    0    6  988    0    6    0    3    3    4]
 [   2    1    1    3  959    1    5    1    1    8]
 [   2    0    0   14    1  864    2    3    5    1]
 [   3    2    3    1    7    6  936    0    0    0]
 [   0    4   10    2    2    0    1 1001    3    5]
 [   4    1    4    8    5    8    3    3  934    4]
 [   3    2    0    5    9    2    0    5    4  979]]


In [43]:
def accuracy(cm):
    diagonal = cm.trace()
    elements = cm.sum()
    return diagonal/elements

In [44]:
print(accuracy(acc))

0.9768
